//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotesBooks.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notes_
    {
        public int NotesId { get; set; }
        public string NotesTitle { get; set; }
        public string Notes { get; set; }
        public System.DateTime Date { get; set; }
    }
}
